services:
  - name: flask-react-app
    type: web
    runtime: python
    plan: free
    buildCommand: "pip install -r requirements.txt && npm install --prefix ../frontend && npm run build --prefix ../frontend"
    startCommand: "gunicorn -b 0.0.0.0:5000 app:app"
    envVars:
      - key: PORT
        value: 5000
      - key: PREVIEW_ENV
        value: "true"
        preview: true

