name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  frontend:
    name: Lint & Format React Frontend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      
      - name: Install system dependencies
        run: sudo apt update && sudo apt install -y libcairo2-dev pkg-config

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: |
          cd frontend
          npm install

      - name: Run ESLint
        run: |
          cd frontend
          npm run lint

      - name: Run Prettier Check
        run: |
          cd frontend
          npm run format

      - name: Build Frontend
        run: |
          cd frontend
          npm run build

  backend:
    name: Lint & Format Flask Backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      
      - name: Remove torch (if installed)
        run: pip uninstall -y torch

      - name: Install Dependencies
        run: |
          cd backend
          pip install -r requirements.txt

      - name: Run Flake8 (Linting)
        run: |
          cd backend
          flake8 .

      - name: Run Black (Formatting Check)
        run: |
          cd backend
          black --check .

  deploy:
    name: Render Deployment - auto-triggered by a ${{ github.event_name }}
    env: 
      SRV_ID: ${{ secrets.SRV_ID }}
      SRV_KEY: ${{ secrets.SRV_KEY }}
      SRV_TK: ${{ secrets.SRV_TK }}
    if: github.event_name == 'push' || github.event_name == 'pull_request'
    needs: 
      - frontend 
      - backend
    runs-on: ubuntu-latest
    steps:
      - run: echo "Job auto-triggered by a ${{ github.event_name }} event..."
      - run: echo "Running on a ${{ runner.os }} server hosted by GitHub..."
      - run: echo "For branch ${{ github.ref }} of repo ${{ github.repository }}..."

      - name: Issue a get request with Render deploy hook
        run: curl "https://api.render.com/deploy/${{ env.SRV_ID }}?key=${{ env.SRV_KEY }}"

      - name: Deploying to Render...
        uses: bounceapp/render-action@0.6.0
        with:
          service-id: ${{ env.SRV_ID }}
          render-token: ${{ env.SRV_TK }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          retries: 50
          wait: 3000
          sleep: 0

      - name: Post PR Preview URL to GitHub
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const url = "https://pr-${{ github.event.pull_request.number }}.onrender.com";
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              body: `🚀 PR Preview deployed: [View here](${url})`
            });
